import { createContext } from "react";
import { IAuthContext, IMesProp } from "../Interfaces/Interfaces";

export const AuthContext = createContext<IAuthContext>({
  createUser: () => {},
  passwordReset: () => {},
  user: {
    accessToken: "",
    auth: {},
    displayName: null,
    email: "",
    emailVerified: false,
    isAnonymous: false,
    metadata: {},
    phoneNumber: null,
    photoURL: null,
    proactiveRefresh: {},
    providerData: [{}],
    providerId: "",
    reloadListener: null,
    reloadUserInfo: {},
    stsTokenManager: {},
    tenantId: null,
    uid: "",
  },
  logOut: () => {},
  signIn: () => {},
  name: "",
  setName: () => {},
  email: "",
  setEmail: () => {},
  userInfo: [],
  setUserInfo: () => {},
  bio: {},
  setBio: () => {},
  // photoUrl: "",
  // setPhotoUrl: () => {},
  messages: [],
  setMessages: () => {},
  storingPost: [],
  setStoringPost: () => {},
});
