import { createContext } from "react";
import { IAuthContext } from "../Interfaces/Interfaces";

export const AuthContext = createContext<IAuthContext>({
  createUser: () => {},
  passwordReset: () => {},
  user: {
    accessToken: "",
    auth: {},
    displayName: null,
    email: "",
    emailVerified: false,
    isAnonymous: false,
    metadata: {},
    phoneNumber: null,
    photoURL: null,
    proactiveRefresh: {},
    providerData: [{}],
    providerId: "",
    reloadListener: null,
    reloadUserInfo: {},
    stsTokenManager: {},
    tenantId: null,
    uid: "",
  },
  setUser: () => {},
  logOut: () => {},
  signIn: () => {},
  name: "",
  setName: () => {},
  email: "",
  setEmail: () => {},
  users: [],
  setUsers: () => {},
  bio: {},
  setBio: () => {},
  posts: [],
  setPosts: () => {},
  textComment: "",
  setTextComment: () => {},
  following: [],
  setFollowing: () => {},
  followers: [],
  setFollowers: () => {},
  liked: [],
  setLiked: () => {},
});
